import './style.css';
import { BleClient } from '@capacitor-community/bluetooth-le';
import { Capacitor } from '@capacitor/core';

const SPP = Capacitor.registerPlugin('BluetoothSerial');
const BMS_SERVICE='0000ffe0-0000-1000-8000-00805f9b34fb';
const BMS_CHAR='0000ffe1-0000-1000-8000-00805f9b34fb';
const SHOW=[201,20,13,83,72,79,87,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,211,13];

const st={bms:{connected:false,voltage:null,current:null,soc:null,temp:null,cells:[],name:'',id:''},ctrl:{connected:false,voltage:null,current:null,rpm:null,temp:null,extTemp:null,status:null,name:'',id:''},gps:{connected:false,speed:null,altitude:null},mode:'ECO',gear:'D'};
const app=document.querySelector('#app');
app.innerHTML=`<main class="tilano-grid">
<header class="tilano-top"><div class="top-left"><div class="brand-mark">M</div><div><div class="brand">MotoMonitor</div><div class="tagline">RIDE · MONITOR · EXPLORE</div></div><div class="connection-icons"><span id="gps-icon" class="conn"><b>⌖</b><small>GPS</small></span><span id="bms-icon" class="conn"><b>♢</b><small>BMS</small></span><span id="votol-icon" class="conn"><b>⌁</b><small>VOTOL</small></span></div></div><div class="clock"><strong id="clock">--:--</strong><span id="date">---</span></div><div class="top-right"><span>☼</span><span>◖</span><button id="settings" class="icon-btn">⚙</button></div></header>
<section class="dashboard-main">
<article class="speed-panel"><div class="eyebrow">SPEED</div><div class="speed-value" id="speed">--</div><div class="speed-unit">km/h</div><div class="mode-box"><button data-mode="prev">‹</button><div><small>MODE</small><strong id="mode">ECO</strong></div><button data-mode="next">›</button></div></article>
<article class="gauge-panel"><div class="rpm-arc"><div class="arc-label">RPM ×1000</div><div class="rpm-scale"><span>0</span><span>2</span><span>4</span><span>6</span><span>8</span><span>10</span><span>12</span></div></div><div class="attitude"><div class="cross">＋</div><div class="horizon"></div><div class="bike">⌁</div><div class="attitude-values"><span><b>--°</b><small>ROLL</small></span><span><b>--°</b><small>PITCH</small></span></div></div><div class="gauge-readout"><div><b id="rpm">--</b><small>RPM</small></div><div><b id="power">--</b><small>POWER</small></div><div><b id="current">--</b><small>CURRENT</small></div></div></article>
<article class="battery-panel"><div class="panel-title">BATTERY <span id="bms-name">JK BMS</span></div><div class="soc-value" id="soc">--%</div><div class="battery-visual"><div id="battery-fill"></div></div><div class="battery-pack"><span id="voltage">-- V</span><span id="cells">--S</span></div><div class="battery-metrics"><div><small>CURRENT</small><b id="bms-current">-- A</b></div><div><small>TEMP</small><b id="bms-temp">-- °C</b></div></div></article>
<article class="lower-telemetry"><div class="gear-card"><small>GEAR</small><strong id="gear">D</strong></div><div class="trip-strip"><div><small>ODO</small><b>-- km</b></div><div><small>TRIP A</small><b>0.0 km</b></div><div><small>RANGE</small><b>-- km</b></div></div><div class="temp-strip"><div><small>MOTOR TEMP</small><b id="motor-temp">-- °C</b></div><div><small>CTRL TEMP</small><b id="ctrl-temp">-- °C</b></div></div></article>
</section>
<section class="media-card"><div class="album-art">♪</div><div class="track"><b>No Title</b><small>No Artist</small><div class="progress"><i></i></div><div class="time"><span>0:00</span><span>--:--</span></div></div><div class="media-controls"><button>l◀</button><button id="play" class="play">▶</button><button>▶l</button></div><div class="volume">◖ <i></i></div></section>
<section class="quick-stats"><div><small>AVG SPEED</small><b id="avg">-- km/h</b></div><div><small>TRIP TIME</small><b id="trip-time">00:00</b></div><div><small>EFFICIENCY</small><b>-- Wh/km</b></div><div><small>ELEVATION</small><b id="elevation">-- m</b></div><div><small>SOC USED</small><b>-- %</b></div></section>
<nav class="bottom-nav"><button class="active" data-page="dashboard">⌂<small>Dashboard</small></button><button data-page="bms">▣<small>BMS</small></button><button data-page="votol">▦<small>VOTOL</small></button><button data-page="map">⌖<small>Map</small></button><button data-page="trip">▥<small>Trip</small></button><button data-page="media">♫<small>Media</small></button><button data-page="settings">⚙<small>Settings</small></button></nav>
<div id="device-picker" class="device-picker hidden"><div class="picker-panel"><div class="picker-head"><div><h2 id="picker-title">Select Bluetooth device</h2><p id="picker-subtitle">Choose a paired device.</p></div><button class="secondary" id="picker-close">Cancel</button></div><div id="picker-list" class="picker-list"></div><button class="secondary picker-refresh" id="picker-refresh">Refresh devices</button></div></div><div id="toast" class="toast hidden"></div></main>`;

const $=s=>document.querySelector(s); const fmt=(x,d=1,u='')=>Number.isFinite(x)?`${x.toFixed(d)}${u}`:`--${u}`;
function render(){const b=st.bms,c=st.ctrl,g=st.gps,p=Number.isFinite(b.voltage)&&Number.isFinite(b.current)?Math.abs(b.voltage*b.current):null,s=Number.isFinite(g.speed)?g.speed:null;$('#speed').textContent=Number.isFinite(s)?Math.round(s):'--';$('#avg').textContent=Number.isFinite(s)?`${Math.round(s)} km/h`:'-- km/h';$('#soc').textContent=Number.isFinite(b.soc)?`${Math.round(b.soc)}%`:'--%';$('#battery-fill').style.width=`${Math.max(0,Math.min(100,b.soc??0))}%`;$('#voltage').textContent=fmt(b.voltage,1,' V');$('#cells').textContent=b.cells.length?`${b.cells.length}S`:'--S';$('#bms-current').textContent=fmt(b.current,1,' A');$('#bms-temp').textContent=fmt(b.temp,1,' °C');$('#rpm').textContent=Number.isFinite(c.rpm)?c.rpm:'--';$('#power').textContent=p==null?'--':`${(p/1000).toFixed(1)} kW`;$('#current').textContent=fmt(c.current,1,' A');$('#motor-temp').textContent=fmt(c.extTemp,1,' °C');$('#ctrl-temp').textContent=fmt(c.temp,1,' °C');$('#gear').textContent=st.gear;$('#mode').textContent=st.mode;$('#bms-name').textContent=b.name?b.name.slice(0,16):'JK BMS';[['#gps-icon',g.connected],['#bms-icon',b.connected],['#votol-icon',c.connected]].forEach(([id,on])=>$(id).classList.toggle('on',on));}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString([],{weekday:'short',day:'2-digit',month:'short',year:'numeric'});}setInterval(clock,1000);clock();
const u16=(b,i)=>b[i]|b[i+1]<<8;const i32=(b,i)=>{const v=(b[i]|b[i+1]<<8|b[i+2]<<16|b[i+3]<<24)>>>0;return v>2147483647?v-4294967296:v};const join=(a,b)=>{const x=new Uint8Array(a.length+b.length);x.set(a);x.set(b,a.length);return x};let jb=new Uint8Array(0);
function parse55(b){if(b.length<46||b[0]!=85||b[1]!=170||b[2]!=235||b[3]!=144)return;const cells=[];for(let i=0;i<32&&6+2*i+1<b.length;i++){const v=u16(b,6+2*i)/1000;if(v>1&&v<5)cells.push(v);else if(i>=20)break}if(cells.length){st.bms.cells=cells;st.bms.voltage=cells.reduce((a,v)=>a+v,0)}}
function parse57(b){if(b.length<20||b[0]!=78||b[1]!=87)return;let p=10,end=b.length-4;while(p<end){const t=b[p++];if(t==121&&p<end){const z=b[p++],cells=[];for(let i=0;i<z/2&&p+1<end;i++,p+=2){const v=u16(b,p)/1000;if(v>1&&v<5)cells.push(v)}if(cells.length){st.bms.cells=cells}continue}if(t==131&&p+3<end){st.bms.voltage=((b[p]<<24)|(b[p+1]<<16)|(b[p+2]<<8)|b[p+3])/1000;p+=4;continue}if(t==132&&p+3<end){st.bms.current=i32(b,p)/1000;p+=4;continue}if(t==133&&p<end){st.bms.soc=b[p++];continue}if(t>=128&&t<=130&&p+1<end){const v=(b[p]<<8)|b[p+1];st.bms.temp=(v&32768)?v-65536:v;p+=2;continue}if([134,138,139,140,142].includes(t)){p++;continue}if([144,145,146,147,148,149,150].includes(t)||t==135){p+=2;continue}if(t==137||t==170)p+=4}}
function jkData(data){jb=join(jb,Uint8Array.from(data));while(jb.length>=4){let s=-1;for(let i=0;i<jb.length-1;i++)if((jb[i]==85&&jb[i+1]==170)||(jb[i]==78&&jb[i+1]==87)){s=i;break}if(s<0){jb=jb.slice(-3);return}if(s)jb=jb.slice(s);if(jb[0]==85){if(jb.length<150)return;parse55(jb.slice(0,150));jb=jb.slice(150)}else{const len=jb[2]<<8|jb[3];if(len<20||jb.length<len)return;parse57(jb.slice(0,len));jb=jb.slice(len)}render()}}
async function connectBms(){try{if(st.bms.connected){await BleClient.disconnect(st.bms.id);st.bms.connected=false;render();return}await BleClient.initialize();const d=await BleClient.requestDevice({acceptAllDevices:true,optionalServices:[BMS_SERVICE]});st.bms.id=d.deviceId;st.bms.name=d.name||d.deviceId;await BleClient.connect(d.deviceId,()=>{st.bms.connected=false;render()});await BleClient.startNotifications(d.deviceId,BMS_SERVICE,BMS_CHAR,v=>jkData(Array.from(new Uint8Array(v.buffer,v.byteOffset,v.byteLength))));st.bms.connected=true;jb=new Uint8Array(0);render();for(const cmd of [0x96,0x95]){const q=new Uint8Array(20);q.set([170,85,144,235,cmd]);let sum=0;for(let i=0;i<19;i++)sum=(sum+q[i])&255;q[19]=sum;await BleClient.writeWithoutResponse(d.deviceId,BMS_SERVICE,BMS_CHAR,new DataView(q.buffer)).catch(()=>{});await new Promise(r=>setTimeout(r,300))}}catch(e){st.bms.connected=false;render();toast(`JK BMS: ${e?.message||e}`)}}
let vb=new Uint8Array(0),poll,rawListener,statusListener;function votolData(data){vb=join(vb,Uint8Array.from(data));while(vb.length>=24){let s=-1;for(let i=0;i<=vb.length-24;i++)if(vb[i]==192&&vb[i+1]==20){s=i;break}if(s<0){vb=vb.slice(-23);return}if(s)vb=vb.slice(s);const b=vb.slice(0,24),v=(b[5]<<8|b[6])/10;let ir=b[7]<<8|b[8];if(ir&32768)ir-=65536;const states=['IDLE','INIT','START','RUN','STOP','BRAKE','WAIT','FAULT'];st.ctrl.voltage=v;st.ctrl.current=ir/10;st.ctrl.rpm=b[14]<<8|b[15];st.ctrl.temp=b[16]-50;st.ctrl.extTemp=b[17]-50;st.ctrl.status=states[b[21]]||`ST:${b[21]}`;vb=vb.slice(24);render()}}
function picker(devices){const list=$('#picker-list');list.innerHTML=devices.length?'':'<div class="empty-device">No paired Bluetooth devices found.</div>';devices.forEach(d=>{const b=document.createElement('button');b.className='device-option';b.innerHTML=`<strong>${d.name||'Unnamed device'}</strong><span>${d.id||d.address||''}</span>`;b.onclick=()=>{$('#device-picker').classList.add('hidden');connectVotol(d)};list.appendChild(b)});$('#device-picker').classList.remove('hidden')}
async function connectVotol(d){try{st.ctrl.id=d.id||d.address;st.ctrl.name=d.name||st.ctrl.id;if(rawListener)await rawListener.remove().catch(()=>{});if(statusListener)await statusListener.remove().catch(()=>{});rawListener=await SPP.addListener('rawData',e=>votolData(e.data||[]));statusListener=await SPP.addListener('status',e=>{st.ctrl.connected=!!e.connected;if(e.name)st.ctrl.name=e.name;render()});await SPP.connectInsecure({id:st.ctrl.id});st.ctrl.connected=true;vb=new Uint8Array(0);render();await SPP.write({data:SHOW});clearInterval(poll);poll=setInterval(()=>SPP.write({data:SHOW}).catch(()=>{}),200)}catch(e){st.ctrl.connected=false;render();toast(`VOTOL SPP: ${e?.message||e}`)}}
async function controller(){try{if(Capacitor.getPlatform()!=='android')return toast('VOTOL Classic SPP tersedia di Android APK');if(st.ctrl.connected){clearInterval(poll);await SPP.disconnect().catch(()=>{});st.ctrl.connected=false;render();return}const r=await SPP.list();picker((r?.devices||[]).filter(x=>x&&(x.id||x.address)))}catch(e){toast(`VOTOL: ${e?.message||e}`)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),1800)}

document.addEventListener('click',e=>{const m=e.target.closest('[data-mode]');if(m){const a=['ECO','NORMAL','SPORT'],i=a.indexOf(st.mode)+(m.dataset.mode==='next'?1:-1);st.mode=a[(i+a.length)%a.length];render()}const p=e.target.closest('[data-page]');if(p){document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));p.classList.add('active');if(p.dataset.page==='bms')connectBms();else if(p.dataset.page==='votol')controller();else if(p.dataset.page!=='dashboard')toast(`${p.dataset.page.toUpperCase()} module — shell ready`)}});
$('#settings').onclick=()=>toast('Settings module — shell ready');$('#play').onclick=()=>toast('Media player bridge ready');$('#picker-close').onclick=()=>$('#device-picker').classList.add('hidden');$('#picker-refresh').onclick=()=>controller();
window.MotoMonitor={state:st,setGps(data){Object.assign(st.gps,data,{connected:true});render()},connectBms,connectVotol:controller};
render();
